language: php

php:
  - 8.1

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer key
  - composer build
  - npm install
  - npm run build

script:
  - php artisan test

services:
  - mysql

notifications:
  email: false