language: php

php:
  - 8.1

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate:fresh --seed --seeder=PermissionSeeder

script:
  - php artisan test

before_install:
  - mysql -e 'CREATE DATABASE laravel_app;'

services:
  - mysql

notifications:
  email: false